### ISSUE TITLE
import resolves to a prerelease version

### ISSUE THREAD

**Issue by DanielKehoe** [jspm/project#71] opened 2020-07-29 14:07 UTC
I'm using LitElement and LitHtml to build custom elements and importing necessary modules using jspm.dev. Custom elements built on LitElement tend to break if multiple versions of LitHtml are imported.

```
import { LitElement, html } from 'https://jspm.dev/lit-element';
import { until } from 'https://jspm.dev/lit-html/directives/until.js';
```
Using the above imports, several of my custom elements broke suddenly after release of LitHtml version 1.3.0-pre.1. As I understand it, LitHtml uses an `instanceof` check to check if a value is a template in order to render it. If two instances of LitHtml get loaded on a page, templates created by one version can't be rendered by the other version. Apparently, importing `until` loads a second version of LitHtml and version conflicts can arise.

When loading LitElement 2.3.1, it seems JSPM resolves the dependency to LitHtml ^1.1.1 with the latest 1.3.0-pre.1 instead of 1.2.1. Loading the `until` directive from 1.2.1 introduces a conflict and the custom element fails. I believe LitElement should better handle the conflict condition (and I'll open an issue there). But perhaps JSPM should not be resolving to a prerelease version? Is this expected behavior?

@hsablonniere has created a JSBin that illustrates the issue: https://jsbin.com/muyipicusu/edit?html,output

Here's the example:

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>

  <script type="module">
    import { LitElement } from 'https://jspm.dev/lit-element@2.3.1';
    import { html } from 'https://jspm.dev/lit-html@1.2.1';
    class HelloWorld extends LitElement {
      render(){
        return html`
          <p>Hello World</p>
        `;
      }
    }
    customElements.define('my-hello', HelloWorld);
  </script>
  
  <my-hello></my-hello>
  
</body>
</html>
```
The output is `[object Object]` (it should be "Hello World").

@hsablonniere commented:

> LitElement has a dependency to lit-html with ^1.1.1 so the tree looks like this:
> `https://jspm.dev/lit-element@2.3.1` => `https://jspm.dev/npm:lit-html@1/lit-html.js` => `https://jspm.dev/npm:lit-html@1.3.0-pre.1`
> Because of how those modules work, it's in conflict with `https://jspm.dev/lit-html@1.2.1`
> I'm not a semver expert but I think the `https://jspm.dev/npm:lit-html@1/lit-html.js` should not resolve to 1.3.0-pre.1 which is marked as next and not stable.

(Thank you to @hsablonniere and the sharp minds on the Polymer Project Slack channel for helping me understand the anomaly.)

**Comment by JayaKrishnaNamburu** [comment] 2020-07-29 16:24
One more place where i started to notice such kind of behaviour is, When i am trying to import `@chakra-ui/button@1.0.0-rc.0` version. Here you can see in the jsfiddle --> https://jsfiddle.net/9hra4qkx/

https://jspm.dev/@chakra-ui/button@1.0.0-rc.0 uses https://jspm.dev/@chakra-ui/spinner@1.0.0-rc.0 which in term uses https://jspm.dev/npm:@chakra-ui/hooks@1.0.0-rc.0 (This package fails) But when independently used without any version pinning it is resolving to latest version of hooks and serving them --> https://jspm.dev/npm:@chakra-ui/hooks

The original package with `@chakra-ui/hooks@1.0.0-rc.0` is present on npm --> `https://www.npmjs.com/package/@chakra-ui/hooks/v/1.0.0-rc.0`

**Comment by guybedford** [comment] 2020-07-29 16:46
Ok I've fixed up the lit-html case - you can see that https://jspm.dev/npm:lit-html@1 is now referencing the correct version instead of the prerelease.

The issue was that the major and minor "aliases" (`https://jspm.dev/npm:pkg@X` and `https://jspm.dev/npm:pkg@X.Y`, including subpaths etc) were being matched to include prereleases. I'm running an update script to fix these up for all other packages as well which should finish soon.

Note that prerelease versions are available if you use a trailing "@" in lookups - `https://jspm.dev/lit-html@` will load the latest version including prereleases. We don't currently support this for major and minor ranges but that could be an option in future.

@JayaKrishnaNamburu your issue seems like it is a different issue - I just ran a rebuild of chakra-ui/hooks and it seems to be working now. The next issue in your bin now seems to be a named export one - let's get another issue going to track that further.

**Comment by guybedford** [comment] 2020-07-29 16:50
@JayaKrishnaNamburu just checked the build logs and it was actually a file system corruption in the analysis file which then failed a re-queued analysis run! Looking into why the re-queue didn't trigger now.

**Comment by JayaKrishnaNamburu** [comment] 2020-07-29 16:51
Thank you @guybedford, let me know if i can help with anything or specify all the details in a new issue separately 😄

**Comment by guybedford** [comment] 2020-07-29 17:00
@JayaKrishnaNamburu I've fixed up the analysis retry queue mechanism for deep dependency trees so that should avoid this from happening again.... the issue is that these component libraries all get published at once and depend on each other's processing.

But there's still a code-level issue in your JSBin case which you may want to follow up in another issue. I suspect this is actually an interop issue with the underlying library and not a jspm bug though.

**Comment by hsablonniere** [comment] 2020-07-29 23:37
@guybedford Awesome reactivity!

**Comment by DanielKehoe** [comment] 2020-07-30 03:23
Thanks @guybedford! The LitHtml issue is resolved.

**Comment by guybedford** [comment] 2020-07-30 03:25
Great... the update script also just finished running finally so all ~45k similar package cases have been resolved as well. Thanks for the clear report!

**Closed by guybedford** 2020-07-30 03:25 UTC

**Comment by DanielKehoe** [comment] 2020-07-30 08:25
For future reference, I've opened an issue on Lit-Html to suggest better handling of the conflicting imports: https://github.com/Polymer/lit-html/issues/1195
